title: LoS Tools Lab
description: Návody, modelová data a příklady využití nástrojů LoS Tools v QGIS

remote_theme: daattali/beautiful-jekyll@6.0.1

navbar-links:
  Domů: "index"
  Začít s LoS Tools: "zacit"
  Modelové příklady: "priklady"
  Ke stažení: "stazeni"
  FAQ: "faq"
  Odkazy: "odkazy"

title-img: ""

author: "Lenka Hromkova"
round-avatar: false

social-network-links:
  github: hromkova/los-tools

share-links-active:
  twitter: false
  facebook: false
  linkedin: false

remove-ads: true
