title: LoS Tools Lab
description: Návody, modelová data a příklady využití nástrojů LoS Tools v QGIS

remote_theme: daattali/beautiful-jekyll@6.0.1

site-css: "/assets/css/custom-styles.css"

navbar-links:
  Domů: "/"
  Začít s LoS Tools: "zacit"
  Modelové příklady: "priklady"
  Ke stažení: "stazeni"
  FAQ: "faq"
  Odkazy: "odkazy"

author: "Lenka Hromková"
round-avatar: false

social-network-links:
  github: hromkova/los-tools
